export interface AirlineInfo {
  code: string; // IATA 2-letter code (e.g. 'SQ', 'AA', 'BA')
  name: string; // Full name (e.g. 'Singapore Airlines')
}

export const AIRLINES: AirlineInfo[] = [
  { code: 'A3', name: 'Aegean Airlines' },
  { code: 'EI', name: 'Aer Lingus' },
  { code: 'SU', name: 'Aeroflot' },
  { code: 'AR', name: 'Aerolíneas Argentinas' },
  { code: 'AM', name: 'Aeroméxico' },
  { code: 'AK', name: 'AirAsia' },
  { code: 'D7', name: 'AirAsia X' },
  { code: 'G9', name: 'Air Arabia' },
  { code: 'KC', name: 'Air Astana' },
  { code: 'BT', name: 'airBaltic' },
  { code: 'AC', name: 'Air Canada' },
  { code: 'CA', name: 'Air China' },
  { code: 'UX', name: 'Air Europa' },
  { code: 'AF', name: 'Air France' },
  { code: 'AI', name: 'Air India' },
  { code: 'IX', name: 'Air India Express' },
  { code: 'MK', name: 'Air Mauritius' },
  { code: 'NZ', name: 'Air New Zealand' },
  { code: 'JU', name: 'Air Serbia' },
  { code: 'TN', name: 'Air Tahiti Nui' },
  { code: 'TS', name: 'Air Transat' },
  { code: 'AS', name: 'Alaska Airlines' },
  { code: 'G4', name: 'Allegiant Air' },
  { code: 'AA', name: 'American Airlines' },
  { code: 'NH', name: 'ANA (All Nippon Airways)' },
  { code: 'OZ', name: 'Asiana Airlines' },
  { code: 'OS', name: 'Austrian Airlines' },
  { code: 'AV', name: 'Avianca' },
  { code: 'AD', name: 'Azul Brazilian Airlines' },
  { code: 'QH', name: 'Bamboo Airways' },
  { code: 'PG', name: 'Bangkok Airways' },
  { code: 'ID', name: 'Batik Air' },
  { code: 'MX', name: 'Breeze Airways' },
  { code: 'BA', name: 'British Airways' },
  { code: 'SN', name: 'Brussels Airlines' },
  { code: 'BW', name: 'Caribbean Airlines' },
  { code: 'CX', name: 'Cathay Pacific' },
  { code: '5J', name: 'Cebu Pacific' },
  { code: 'CI', name: 'China Airlines' },
  { code: 'MU', name: 'China Eastern Airlines' },
  { code: 'CZ', name: 'China Southern Airlines' },
  { code: 'DE', name: 'Condor' },
  { code: 'CM', name: 'Copa Airlines' },
  { code: 'OU', name: 'Croatia Airlines' },
  { code: 'DL', name: 'Delta Air Lines' },
  { code: 'U2', name: 'easyJet' },
  { code: 'MS', name: 'EgyptAir' },
  { code: 'LY', name: 'El Al Israel Airlines' },
  { code: 'EK', name: 'Emirates' },
  { code: 'ET', name: 'Ethiopian Airlines' },
  { code: 'EY', name: 'Etihad Airways' },
  { code: 'EW', name: 'Eurowings' },
  { code: 'BR', name: 'EVA Air' },
  { code: 'FJ', name: 'Fiji Airways' },
  { code: 'AY', name: 'Finnair' },
  { code: 'FZ', name: 'flydubai' },
  { code: 'XY', name: 'flynas' },
  { code: 'F9', name: 'Frontier Airlines' },
  { code: 'GA', name: 'Garuda Indonesia' },
  { code: 'G3', name: 'GOL Airlines' },
  { code: 'GF', name: 'Gulf Air' },
  { code: 'HU', name: 'Hainan Airlines' },
  { code: 'HA', name: 'Hawaiian Airlines' },
  { code: 'HX', name: 'Hong Kong Airlines' },
  { code: 'IB', name: 'Iberia' },
  { code: 'FI', name: 'Icelandair' },
  { code: '6E', name: 'IndiGo' },
  { code: 'AZ', name: 'ITA Airways' },
  { code: 'JL', name: 'Japan Airlines' },
  { code: 'J9', name: 'Jazeera Airways' },
  { code: '7C', name: 'Jeju Air' },
  { code: 'B6', name: 'JetBlue Airways' },
  { code: 'JA', name: 'JetSMART' },
  { code: 'JQ', name: 'Jetstar Airways' },
  { code: 'LJ', name: 'Jin Air' },
  { code: 'KQ', name: 'Kenya Airways' },
  { code: 'KL', name: 'KLM Royal Dutch Airlines' },
  { code: 'KE', name: 'Korean Air' },
  { code: 'LA', name: 'LATAM Airlines' },
  { code: 'JT', name: 'Lion Air' },
  { code: 'LO', name: 'LOT Polish Airlines' },
  { code: 'LH', name: 'Lufthansa' },
  { code: 'MH', name: 'Malaysia Airlines' },
  { code: 'ME', name: 'Middle East Airlines' },
  { code: 'DD', name: 'Nok Air' },
  { code: 'DY', name: 'Norwegian Air Shuttle' },
  { code: 'WY', name: 'Oman Air' },
  { code: 'PK', name: 'Pakistan International Airlines' },
  { code: 'MM', name: 'Peach Aviation' },
  { code: 'PC', name: 'Pegasus Airlines' },
  { code: 'PR', name: 'Philippine Airlines' },
  { code: 'OG', name: 'PLAY' },
  { code: 'PD', name: 'Porter Airlines' },
  { code: 'QF', name: 'Qantas' },
  { code: 'QR', name: 'Qatar Airways' },
  { code: 'ZL', name: 'Rex Airlines' },
  { code: 'AT', name: 'Royal Air Maroc' },
  { code: 'RJ', name: 'Royal Jordanian' },
  { code: 'WB', name: 'RwandAir' },
  { code: 'FR', name: 'Ryanair' },
  { code: 'SK', name: 'SAS (Scandinavian Airlines)' },
  { code: 'SV', name: 'Saudia' },
  { code: 'TR', name: 'Scoot' },
  { code: 'SQ', name: 'Singapore Airlines' },
  { code: 'QS', name: 'Smartwings' },
  { code: 'SA', name: 'South African Airways' },
  { code: 'WN', name: 'Southwest Airlines' },
  { code: 'SG', name: 'SpiceJet' },
  { code: 'NK', name: 'Spirit Airlines' },
  { code: '9C', name: 'Spring Airlines' },
  { code: 'UL', name: 'SriLankan Airlines' },
  { code: 'JX', name: 'Starlux Airlines' },
  { code: 'SY', name: 'Sun Country Airlines' },
  { code: 'XQ', name: 'SunExpress' },
  { code: 'LX', name: 'Swiss International Air Lines' },
  { code: 'TP', name: 'TAP Air Portugal' },
  { code: 'RO', name: 'TAROM' },
  { code: 'TG', name: 'Thai Airways' },
  { code: 'SL', name: 'Thai Lion Air' },
  { code: 'TO', name: 'Transavia' },
  { code: 'TK', name: 'Turkish Airlines' },
  { code: 'TW', name: "T'way Air" },
  { code: 'UA', name: 'United Airlines' },
  { code: 'HY', name: 'Uzbekistan Airways' },
  { code: 'VJ', name: 'VietJet Air' },
  { code: 'VN', name: 'Vietnam Airlines' },
  { code: 'VS', name: 'Virgin Atlantic' },
  { code: 'VA', name: 'Virgin Australia' },
  { code: 'UK', name: 'Vistara' },
  { code: 'Y4', name: 'Volaris' },
  { code: 'VY', name: 'Vueling' },
  { code: 'WS', name: 'WestJet' },
  { code: 'W6', name: 'Wizz Air' },
  { code: 'MF', name: 'Xiamen Airlines' },
  { code: 'ZG', name: 'ZIPAIR' },
];
