export interface AirportInfo {
  code: string; // IATA 3-letter code (e.g. 'SIN', 'NRT', 'JFK')
  name: string; // City + airport name (e.g. 'Singapore Changi')
  city: string; // City name for search matching (e.g. 'Singapore')
}

export const AIRPORTS: AirportInfo[] = [
  { code: 'ABJ', name: 'Abidjan Félix-Houphouët-Boigny', city: 'Abidjan' },
  { code: 'ABQ', name: 'Albuquerque International Sunport', city: 'Albuquerque' },
  { code: 'ABV', name: 'Abuja Nnamdi Azikiwe', city: 'Abuja' },
  { code: 'ACC', name: 'Accra Kotoka', city: 'Accra' },
  { code: 'ADD', name: 'Addis Ababa Bole', city: 'Addis Ababa' },
  { code: 'ADL', name: 'Adelaide Airport', city: 'Adelaide' },
  { code: 'AKL', name: 'Auckland Airport', city: 'Auckland' },
  { code: 'ALG', name: 'Algiers Houari Boumediene', city: 'Algiers' },
  { code: 'AMS', name: 'Amsterdam Schiphol', city: 'Amsterdam' },
  { code: 'ANC', name: 'Anchorage Ted Stevens', city: 'Anchorage' },
  { code: 'ARN', name: 'Stockholm Arlanda', city: 'Stockholm' },
  { code: 'ATH', name: 'Athens Eleftherios Venizelos', city: 'Athens' },
  { code: 'ATL', name: 'Atlanta Hartsfield-Jackson', city: 'Atlanta' },
  { code: 'AUH', name: 'Abu Dhabi Zayed', city: 'Abu Dhabi' },
  { code: 'AUS', name: 'Austin-Bergstrom', city: 'Austin' },
  { code: 'BAH', name: 'Bahrain International', city: 'Bahrain' },
  { code: 'BCN', name: 'Barcelona El Prat', city: 'Barcelona' },
  { code: 'BER', name: 'Berlin Brandenburg', city: 'Berlin' },
  { code: 'BGY', name: 'Milan Bergamo', city: 'Bergamo' },
  { code: 'BHX', name: 'Birmingham Airport', city: 'Birmingham' },
  { code: 'BKK', name: 'Bangkok Suvarnabhumi', city: 'Bangkok' },
  { code: 'BLR', name: 'Bengaluru Kempegowda', city: 'Bengaluru' },
  { code: 'BNA', name: 'Nashville International', city: 'Nashville' },
  { code: 'BNE', name: 'Brisbane Airport', city: 'Brisbane' },
  { code: 'BOG', name: 'Bogotá El Dorado', city: 'Bogotá' },
  { code: 'BOM', name: 'Mumbai Chhatrapati Shivaji Maharaj', city: 'Mumbai' },
  { code: 'BOS', name: 'Boston Logan', city: 'Boston' },
  { code: 'BRU', name: 'Brussels Airport', city: 'Brussels' },
  { code: 'BSB', name: 'Brasília International', city: 'Brasília' },
  { code: 'BUD', name: 'Budapest Ferenc Liszt', city: 'Budapest' },
  { code: 'BUF', name: 'Buffalo Niagara', city: 'Buffalo' },
  { code: 'BWI', name: 'Baltimore/Washington International', city: 'Baltimore' },
  { code: 'CAI', name: 'Cairo International', city: 'Cairo' },
  { code: 'CAN', name: 'Guangzhou Baiyun', city: 'Guangzhou' },
  { code: 'CCU', name: 'Kolkata Netaji Subhas Chandra Bose', city: 'Kolkata' },
  { code: 'CDG', name: 'Paris Charles de Gaulle', city: 'Paris' },
  { code: 'CEB', name: 'Cebu Mactan', city: 'Cebu' },
  { code: 'CGK', name: 'Jakarta Soekarno-Hatta', city: 'Jakarta' },
  { code: 'CHC', name: 'Christchurch International', city: 'Christchurch' },
  { code: 'CKG', name: 'Chongqing Jiangbei', city: 'Chongqing' },
  { code: 'CLE', name: 'Cleveland Hopkins', city: 'Cleveland' },
  { code: 'CLT', name: 'Charlotte Douglas', city: 'Charlotte' },
  { code: 'CMB', name: 'Colombo Bandaranaike', city: 'Colombo' },
  { code: 'CMN', name: 'Casablanca Mohammed V', city: 'Casablanca' },
  { code: 'CNX', name: 'Chiang Mai International', city: 'Chiang Mai' },
  { code: 'CPH', name: 'Copenhagen Kastrup', city: 'Copenhagen' },
  { code: 'CPT', name: 'Cape Town International', city: 'Cape Town' },
  { code: 'CTU', name: 'Chengdu Tianfu', city: 'Chengdu' },
  { code: 'CUN', name: 'Cancún International', city: 'Cancún' },
  { code: 'CVG', name: 'Cincinnati/Northern Kentucky', city: 'Cincinnati' },
  { code: 'DAD', name: 'Da Nang International', city: 'Da Nang' },
  { code: 'DAR', name: 'Dar es Salaam Julius Nyerere', city: 'Dar es Salaam' },
  { code: 'DCA', name: 'Washington Reagan National', city: 'Washington D.C.' },
  { code: 'DEL', name: 'Delhi Indira Gandhi', city: 'Delhi' },
  { code: 'DEN', name: 'Denver International', city: 'Denver' },
  { code: 'DFW', name: 'Dallas/Fort Worth International', city: 'Dallas' },
  { code: 'DME', name: 'Moscow Domodedovo', city: 'Moscow' },
  { code: 'DMK', name: 'Bangkok Don Mueang', city: 'Bangkok' },
  { code: 'DOH', name: 'Doha Hamad', city: 'Doha' },
  { code: 'DPS', name: 'Bali Ngurah Rai', city: 'Bali' },
  { code: 'DRS', name: 'Dresden Airport', city: 'Dresden' },
  { code: 'DTW', name: 'Detroit Metropolitan Wayne County', city: 'Detroit' },
  { code: 'DUB', name: 'Dublin Airport', city: 'Dublin' },
  { code: 'DUS', name: 'Düsseldorf Airport', city: 'Düsseldorf' },
  { code: 'DXB', name: 'Dubai International', city: 'Dubai' },
  { code: 'EDI', name: 'Edinburgh Airport', city: 'Edinburgh' },
  { code: 'EWR', name: 'Newark Liberty', city: 'Newark' },
  { code: 'EZE', name: 'Buenos Aires Ezeiza', city: 'Buenos Aires' },
  { code: 'FCO', name: 'Rome Fiumicino', city: 'Rome' },
  { code: 'FLL', name: 'Fort Lauderdale-Hollywood', city: 'Fort Lauderdale' },
  { code: 'FRA', name: 'Frankfurt Airport', city: 'Frankfurt' },
  { code: 'FUK', name: 'Fukuoka Airport', city: 'Fukuoka' },
  { code: 'GIG', name: 'Rio de Janeiro Galeão', city: 'Rio de Janeiro' },
  { code: 'GOT', name: 'Gothenburg Landvetter', city: 'Gothenburg' },
  { code: 'GRU', name: 'São Paulo Guarulhos', city: 'São Paulo' },
  { code: 'GVA', name: 'Geneva Airport', city: 'Geneva' },
  { code: 'HAM', name: 'Hamburg Airport', city: 'Hamburg' },
  { code: 'HAN', name: 'Hanoi Noi Bai', city: 'Hanoi' },
  { code: 'HEL', name: 'Helsinki Vantaa', city: 'Helsinki' },
  { code: 'HKG', name: 'Hong Kong International', city: 'Hong Kong' },
  { code: 'HKT', name: 'Phuket International', city: 'Phuket' },
  { code: 'HND', name: 'Tokyo Haneda', city: 'Tokyo' },
  { code: 'HNL', name: 'Honolulu Daniel K. Inouye', city: 'Honolulu' },
  { code: 'HYD', name: 'Hyderabad Rajiv Gandhi', city: 'Hyderabad' },
  { code: 'IAD', name: 'Washington Dulles', city: 'Washington D.C.' },
  { code: 'IAH', name: 'Houston George Bush Intercontinental', city: 'Houston' },
  { code: 'ICN', name: 'Seoul Incheon', city: 'Seoul' },
  { code: 'IND', name: 'Indianapolis International', city: 'Indianapolis' },
  { code: 'IST', name: 'Istanbul Airport', city: 'Istanbul' },
  { code: 'JAX', name: 'Jacksonville International', city: 'Jacksonville' },
  { code: 'JED', name: 'Jeddah King Abdulaziz', city: 'Jeddah' },
  { code: 'JFK', name: 'New York John F. Kennedy', city: 'New York' },
  { code: 'JNB', name: 'Johannesburg O.R. Tambo', city: 'Johannesburg' },
  { code: 'KHI', name: 'Karachi Jinnah', city: 'Karachi' },
  { code: 'KIX', name: 'Osaka Kansai', city: 'Osaka' },
  { code: 'KUL', name: 'Kuala Lumpur International', city: 'Kuala Lumpur' },
  { code: 'KWI', name: 'Kuwait International', city: 'Kuwait City' },
  { code: 'LAS', name: 'Las Vegas Harry Reid', city: 'Las Vegas' },
  { code: 'LAX', name: 'Los Angeles International', city: 'Los Angeles' },
  { code: 'LED', name: 'St Petersburg Pulkovo', city: 'St Petersburg' },
  { code: 'LGA', name: 'New York LaGuardia', city: 'New York' },
  { code: 'LGW', name: 'London Gatwick', city: 'London' },
  { code: 'LHR', name: 'London Heathrow', city: 'London' },
  { code: 'LIM', name: 'Lima Jorge Chávez', city: 'Lima' },
  { code: 'LIS', name: 'Lisbon Humberto Delgado', city: 'Lisbon' },
  { code: 'LOS', name: 'Lagos Murtala Muhammed', city: 'Lagos' },
  { code: 'LTN', name: 'London Luton', city: 'London' },
  { code: 'MAA', name: 'Chennai International', city: 'Chennai' },
  { code: 'MAD', name: 'Madrid Barajas', city: 'Madrid' },
  { code: 'MAN', name: 'Manchester Airport', city: 'Manchester' },
  { code: 'MBJ', name: 'Montego Bay Sangster', city: 'Montego Bay' },
  { code: 'MCI', name: 'Kansas City International', city: 'Kansas City' },
  { code: 'MCO', name: 'Orlando International', city: 'Orlando' },
  { code: 'MCT', name: 'Muscat International', city: 'Muscat' },
  { code: 'MDE', name: 'Medellín José María Córdova', city: 'Medellín' },
  { code: 'MEL', name: 'Melbourne Tullamarine', city: 'Melbourne' },
  { code: 'MEX', name: 'Mexico City International', city: 'Mexico City' },
  { code: 'MIA', name: 'Miami International', city: 'Miami' },
  { code: 'MKE', name: 'Milwaukee Mitchell', city: 'Milwaukee' },
  { code: 'MLA', name: 'Malta International', city: 'Malta' },
  { code: 'MNL', name: 'Manila Ninoy Aquino', city: 'Manila' },
  { code: 'MRU', name: 'Mauritius Sir Seewoosagur Ramgoolam', city: 'Mauritius' },
  { code: 'MSP', name: 'Minneapolis-Saint Paul', city: 'Minneapolis' },
  { code: 'MSY', name: 'New Orleans Louis Armstrong', city: 'New Orleans' },
  { code: 'MUC', name: 'Munich Airport', city: 'Munich' },
  { code: 'MXP', name: 'Milan Malpensa', city: 'Milan' },
  { code: 'NBO', name: 'Nairobi Jomo Kenyatta', city: 'Nairobi' },
  { code: 'NCE', name: "Nice Côte d'Azur", city: 'Nice' },
  { code: 'NGO', name: 'Nagoya Chubu Centrair', city: 'Nagoya' },
  { code: 'NRT', name: 'Tokyo Narita', city: 'Tokyo' },
  { code: 'OAK', name: 'Oakland International', city: 'Oakland' },
  { code: 'OKA', name: 'Okinawa Naha', city: 'Okinawa' },
  { code: 'OPO', name: 'Porto Francisco Sá Carneiro', city: 'Porto' },
  { code: 'ORD', name: "Chicago O'Hare", city: 'Chicago' },
  { code: 'ORY', name: 'Paris Orly', city: 'Paris' },
  { code: 'OSL', name: 'Oslo Gardermoen', city: 'Oslo' },
  { code: 'PBI', name: 'Palm Beach International', city: 'West Palm Beach' },
  { code: 'PDX', name: 'Portland International', city: 'Portland' },
  { code: 'PEK', name: 'Beijing Capital', city: 'Beijing' },
  { code: 'PER', name: 'Perth Airport', city: 'Perth' },
  { code: 'PHL', name: 'Philadelphia International', city: 'Philadelphia' },
  { code: 'PHX', name: 'Phoenix Sky Harbor', city: 'Phoenix' },
  { code: 'PIT', name: 'Pittsburgh International', city: 'Pittsburgh' },
  { code: 'PMI', name: 'Palma de Mallorca', city: 'Palma de Mallorca' },
  { code: 'PNH', name: 'Phnom Penh International', city: 'Phnom Penh' },
  { code: 'PRG', name: 'Prague Václav Havel', city: 'Prague' },
  { code: 'PTY', name: 'Panama City Tocumen', city: 'Panama City' },
  { code: 'PUS', name: 'Busan Gimhae', city: 'Busan' },
  { code: 'PVG', name: 'Shanghai Pudong', city: 'Shanghai' },
  { code: 'RDU', name: 'Raleigh-Durham International', city: 'Raleigh' },
  { code: 'RGN', name: 'Yangon International', city: 'Yangon' },
  { code: 'RIX', name: 'Riga International', city: 'Riga' },
  { code: 'RSW', name: 'Fort Myers Southwest Florida', city: 'Fort Myers' },
  { code: 'RUH', name: 'Riyadh King Khalid', city: 'Riyadh' },
  { code: 'SAN', name: 'San Diego International', city: 'San Diego' },
  { code: 'SAT', name: 'San Antonio International', city: 'San Antonio' },
  { code: 'SAW', name: 'Istanbul Sabiha Gökçen', city: 'Istanbul' },
  { code: 'SCL', name: 'Santiago Arturo Merino Benítez', city: 'Santiago' },
  { code: 'SEA', name: 'Seattle-Tacoma International', city: 'Seattle' },
  { code: 'SFO', name: 'San Francisco International', city: 'San Francisco' },
  { code: 'SGN', name: 'Ho Chi Minh City Tan Son Nhat', city: 'Ho Chi Minh City' },
  { code: 'SHA', name: 'Shanghai Hongqiao', city: 'Shanghai' },
  { code: 'SIN', name: 'Singapore Changi', city: 'Singapore' },
  { code: 'SJC', name: 'San José Mineta', city: 'San Jose' },
  { code: 'SJU', name: 'San Juan Luis Muñoz Marín', city: 'San Juan' },
  { code: 'SLC', name: 'Salt Lake City International', city: 'Salt Lake City' },
  { code: 'SMF', name: 'Sacramento International', city: 'Sacramento' },
  { code: 'SNN', name: 'Shannon Airport', city: 'Shannon' },
  { code: 'SOF', name: 'Sofia Airport', city: 'Sofia' },
  { code: 'STL', name: 'St Louis Lambert', city: 'St Louis' },
  { code: 'STN', name: 'London Stansted', city: 'London' },
  { code: 'STR', name: 'Stuttgart Airport', city: 'Stuttgart' },
  { code: 'SVG', name: 'Stavanger Sola', city: 'Stavanger' },
  { code: 'SVO', name: 'Moscow Sheremetyevo', city: 'Moscow' },
  { code: 'SXM', name: 'Sint Maarten Princess Juliana', city: 'Sint Maarten' },
  { code: 'SYD', name: 'Sydney Kingsford Smith', city: 'Sydney' },
  { code: 'SZX', name: "Shenzhen Bao'an", city: 'Shenzhen' },
  { code: 'TLV', name: 'Tel Aviv Ben Gurion', city: 'Tel Aviv' },
  { code: 'TPA', name: 'Tampa International', city: 'Tampa' },
  { code: 'TPE', name: 'Taipei Taoyuan', city: 'Taipei' },
  { code: 'TRD', name: 'Trondheim Værnes', city: 'Trondheim' },
  { code: 'TSA', name: 'Taipei Songshan', city: 'Taipei' },
  { code: 'TUN', name: 'Tunis-Carthage', city: 'Tunis' },
  { code: 'VCE', name: 'Venice Marco Polo', city: 'Venice' },
  { code: 'VIE', name: 'Vienna International', city: 'Vienna' },
  { code: 'VNO', name: 'Vilnius Airport', city: 'Vilnius' },
  { code: 'WAW', name: 'Warsaw Chopin', city: 'Warsaw' },
  { code: 'WLG', name: 'Wellington International', city: 'Wellington' },
  { code: 'XIY', name: "Xi'an Xianyang", city: "Xi'an" },
  { code: 'YEG', name: 'Edmonton International', city: 'Edmonton' },
  { code: 'YOW', name: 'Ottawa Macdonald-Cartier', city: 'Ottawa' },
  { code: 'YUL', name: 'Montréal Trudeau', city: 'Montréal' },
  { code: 'YVR', name: 'Vancouver International', city: 'Vancouver' },
  { code: 'YYC', name: 'Calgary International', city: 'Calgary' },
  { code: 'YYZ', name: 'Toronto Pearson', city: 'Toronto' },
  { code: 'ZAG', name: 'Zagreb Franjo Tuđman', city: 'Zagreb' },
  { code: 'ZRH', name: 'Zurich Airport', city: 'Zurich' },
];
