export interface CruisePortInfo {
  name: string; // Port terminal name (e.g., 'Port of Miami')
  city: string; // City name (e.g., 'Miami')
  country: string; // Country (e.g., 'United States')
  region: string; // Region for categorization (e.g., 'Caribbean', 'Mediterranean')
}

export const CRUISE_PORTS: CruisePortInfo[] = [
  {
    name: 'Port of Abu Dhabi',
    city: 'Abu Dhabi',
    country: 'United Arab Emirates',
    region: 'Middle East',
  },
  { name: 'Port of Acapulco', city: 'Acapulco', country: 'Mexico', region: 'Mexican Riviera' },
  { name: 'Port of Ajaccio', city: 'Ajaccio', country: 'France', region: 'Mediterranean' },
  { name: 'Port of Akureyri', city: 'Akureyri', country: 'Iceland', region: 'Northern Europe' },
  { name: 'Port of Alesund', city: 'Alesund', country: 'Norway', region: 'Northern Europe' },
  { name: 'Port of Alexandria', city: 'Alexandria', country: 'Egypt', region: 'Mediterranean' },
  {
    name: 'Port of Amber Cove',
    city: 'Amber Cove',
    country: 'Dominican Republic',
    region: 'Caribbean',
  },
  {
    name: 'Port of Amsterdam',
    city: 'Amsterdam',
    country: 'Netherlands',
    region: 'Northern Europe',
  },
  { name: 'Port of Auckland', city: 'Auckland', country: 'New Zealand', region: 'Asia Pacific' },
  {
    name: 'Port of Baltimore',
    city: 'Baltimore',
    country: 'United States',
    region: 'US East Coast',
  },
  {
    name: 'Port of Bangkok (Laem Chabang)',
    city: 'Bangkok',
    country: 'Thailand',
    region: 'Asia Pacific',
  },
  { name: 'Port of Barcelona', city: 'Barcelona', country: 'Spain', region: 'Mediterranean' },
  { name: 'Port of Bari', city: 'Bari', country: 'Italy', region: 'Mediterranean' },
  {
    name: 'Port of Bayonne (Cape Liberty)',
    city: 'Bayonne',
    country: 'United States',
    region: 'US East Coast',
  },
  { name: 'Port of Belfast', city: 'Belfast', country: 'United Kingdom', region: 'UK & Ireland' },
  { name: 'Port of Belize City', city: 'Belize City', country: 'Belize', region: 'Caribbean' },
  { name: 'Port of Bergen', city: 'Bergen', country: 'Norway', region: 'Northern Europe' },
  {
    name: 'Port of Bermuda (Royal Naval Dockyard)',
    city: 'Bermuda',
    country: 'Bermuda',
    region: 'Caribbean',
  },
  {
    name: 'Port of Bora Bora',
    city: 'Bora Bora',
    country: 'French Polynesia',
    region: 'South Pacific',
  },
  { name: 'Port of Bordeaux', city: 'Bordeaux', country: 'France', region: 'Northern Europe' },
  {
    name: 'Port of Boston (Black Falcon)',
    city: 'Boston',
    country: 'United States',
    region: 'US East Coast',
  },
  { name: 'Port of Bridgetown', city: 'Bridgetown', country: 'Barbados', region: 'Caribbean' },
  { name: 'Port of Brisbane', city: 'Brisbane', country: 'Australia', region: 'Asia Pacific' },
  {
    name: 'Port of Buenos Aires',
    city: 'Buenos Aires',
    country: 'Argentina',
    region: 'South America',
  },
  {
    name: 'Port of Cabo San Lucas',
    city: 'Cabo San Lucas',
    country: 'Mexico',
    region: 'Mexican Riviera',
  },
  { name: 'Port of Cadiz', city: 'Cadiz', country: 'Spain', region: 'Mediterranean' },
  {
    name: 'Port Canaveral',
    city: 'Cape Canaveral',
    country: 'United States',
    region: 'US East Coast',
  },
  { name: 'Port of Cannes', city: 'Cannes', country: 'France', region: 'Mediterranean' },
  { name: 'Port of Cape Town', city: 'Cape Town', country: 'South Africa', region: 'Africa' },
  { name: 'Port of Cartagena', city: 'Cartagena', country: 'Colombia', region: 'Caribbean' },
  { name: 'Port of Casablanca', city: 'Casablanca', country: 'Morocco', region: 'Africa' },
  { name: 'Port of Castries', city: 'Castries', country: 'Saint Lucia', region: 'Caribbean' },
  {
    name: 'Port of Charleston',
    city: 'Charleston',
    country: 'United States',
    region: 'US East Coast',
  },
  {
    name: 'Port of Christchurch (Lyttelton)',
    city: 'Christchurch',
    country: 'New Zealand',
    region: 'Asia Pacific',
  },
  {
    name: 'Port of Civitavecchia (Rome)',
    city: 'Civitavecchia',
    country: 'Italy',
    region: 'Mediterranean',
  },
  { name: 'CocoCay (Perfect Day)', city: 'CocoCay', country: 'Bahamas', region: 'Caribbean' },
  { name: 'Port of Colombo', city: 'Colombo', country: 'Sri Lanka', region: 'Asia Pacific' },
  { name: 'Port of Colon', city: 'Colon', country: 'Panama', region: 'Caribbean' },
  { name: 'Port of Copenhagen', city: 'Copenhagen', country: 'Denmark', region: 'Northern Europe' },
  { name: 'Port of Corfu', city: 'Corfu', country: 'Greece', region: 'Mediterranean' },
  { name: 'Port of Costa Maya', city: 'Costa Maya', country: 'Mexico', region: 'Caribbean' },
  { name: 'Port of Cozumel', city: 'Cozumel', country: 'Mexico', region: 'Caribbean' },
  { name: 'Port of Dakar', city: 'Dakar', country: 'Senegal', region: 'Africa' },
  { name: 'Port of Dover', city: 'Dover', country: 'United Kingdom', region: 'UK & Ireland' },
  {
    name: 'Port of Dubai (Mina Rashid)',
    city: 'Dubai',
    country: 'United Arab Emirates',
    region: 'Middle East',
  },
  { name: 'Port of Dublin', city: 'Dublin', country: 'Ireland', region: 'UK & Ireland' },
  { name: 'Port of Dubrovnik', city: 'Dubrovnik', country: 'Croatia', region: 'Mediterranean' },
  {
    name: 'Port of Dunedin (Port Chalmers)',
    city: 'Dunedin',
    country: 'New Zealand',
    region: 'Asia Pacific',
  },
  { name: 'Port of Durban', city: 'Durban', country: 'South Africa', region: 'Africa' },
  {
    name: 'Port of Edinburgh (Leith)',
    city: 'Edinburgh',
    country: 'United Kingdom',
    region: 'UK & Ireland',
  },
  { name: 'Port of Ensenada', city: 'Ensenada', country: 'Mexico', region: 'Mexican Riviera' },
  { name: 'Port of Falmouth', city: 'Falmouth', country: 'Jamaica', region: 'Caribbean' },
  { name: 'Port of Flam', city: 'Flam', country: 'Norway', region: 'Northern Europe' },
  {
    name: 'Port of Florence/Pisa (Livorno)',
    city: 'Florence',
    country: 'Italy',
    region: 'Mediterranean',
  },
  {
    name: 'Port Everglades',
    city: 'Fort Lauderdale',
    country: 'United States',
    region: 'US East Coast',
  },
  {
    name: 'Port of Frederiksted',
    city: 'Frederiksted',
    country: 'US Virgin Islands',
    region: 'Caribbean',
  },
  {
    name: 'Port of Fremantle (Perth)',
    city: 'Fremantle',
    country: 'Australia',
    region: 'Asia Pacific',
  },
  {
    name: 'Port of Funchal',
    city: 'Funchal',
    country: 'Portugal',
    region: 'Canary Islands & Atlantic',
  },
  {
    name: 'Port of Galveston',
    city: 'Galveston',
    country: 'United States',
    region: 'US Gulf Coast',
  },
  { name: 'Port of Gdansk', city: 'Gdansk', country: 'Poland', region: 'Northern Europe' },
  { name: 'Port of Geiranger', city: 'Geiranger', country: 'Norway', region: 'Northern Europe' },
  { name: 'Port of Genoa', city: 'Genoa', country: 'Italy', region: 'Mediterranean' },
  { name: 'Port of Gibraltar', city: 'Gibraltar', country: 'Gibraltar', region: 'Mediterranean' },
  {
    name: 'Port of Grand Cayman (Georgetown)',
    city: 'Grand Cayman',
    country: 'Cayman Islands',
    region: 'Caribbean',
  },
  {
    name: 'Port of Grand Turk',
    city: 'Grand Turk',
    country: 'Turks and Caicos',
    region: 'Caribbean',
  },
  { name: 'Great Stirrup Cay', city: 'Great Stirrup Cay', country: 'Bahamas', region: 'Caribbean' },
  {
    name: 'Port of Greenock (Glasgow)',
    city: 'Greenock',
    country: 'United Kingdom',
    region: 'UK & Ireland',
  },
  { name: 'Port of Haifa', city: 'Haifa', country: 'Israel', region: 'Mediterranean' },
  { name: 'Port of Halifax', city: 'Halifax', country: 'Canada', region: 'Canada & New England' },
  { name: 'Port of Hamburg', city: 'Hamburg', country: 'Germany', region: 'Northern Europe' },
  { name: 'Harvest Caye', city: 'Harvest Caye', country: 'Belize', region: 'Caribbean' },
  { name: 'Port of Havana', city: 'Havana', country: 'Cuba', region: 'Caribbean' },
  { name: 'Port of Helsinki', city: 'Helsinki', country: 'Finland', region: 'Northern Europe' },
  {
    name: 'Port of Ho Chi Minh City (Phu My)',
    city: 'Ho Chi Minh City',
    country: 'Vietnam',
    region: 'Asia Pacific',
  },
  { name: 'Port of Hobart', city: 'Hobart', country: 'Australia', region: 'Asia Pacific' },
  { name: 'Port of Hong Kong', city: 'Hong Kong', country: 'China', region: 'Asia Pacific' },
  { name: 'Port of Honolulu', city: 'Honolulu', country: 'United States', region: 'Hawaii' },
  { name: 'Port of Huatulco', city: 'Huatulco', country: 'Mexico', region: 'Mexican Riviera' },
  {
    name: 'Port of Icy Strait Point',
    city: 'Icy Strait Point',
    country: 'United States',
    region: 'Alaska',
  },
  { name: 'Port of Istanbul', city: 'Istanbul', country: 'Turkey', region: 'Mediterranean' },
  { name: 'Port of Juneau', city: 'Juneau', country: 'United States', region: 'Alaska' },
  { name: 'Port of Kahului (Maui)', city: 'Kahului', country: 'United States', region: 'Hawaii' },
  { name: 'Port of Ketchikan', city: 'Ketchikan', country: 'United States', region: 'Alaska' },
  { name: 'Port of Key West', city: 'Key West', country: 'United States', region: 'US East Coast' },
  { name: 'Port of Kiel', city: 'Kiel', country: 'Germany', region: 'Northern Europe' },
  { name: 'Port of Kobe', city: 'Kobe', country: 'Japan', region: 'Asia Pacific' },
  { name: 'Port of Kotor', city: 'Kotor', country: 'Montenegro', region: 'Mediterranean' },
  {
    name: 'Port of Kusadasi (Ephesus)',
    city: 'Kusadasi',
    country: 'Turkey',
    region: 'Mediterranean',
  },
  { name: 'Labadee', city: 'Labadee', country: 'Haiti', region: 'Caribbean' },
  {
    name: 'Port of Las Palmas',
    city: 'Las Palmas',
    country: 'Spain',
    region: 'Canary Islands & Atlantic',
  },
  {
    name: 'Port of Le Havre (Paris)',
    city: 'Le Havre',
    country: 'France',
    region: 'Northern Europe',
  },
  { name: 'Port of Lima (Callao)', city: 'Lima', country: 'Peru', region: 'South America' },
  { name: 'Port of Lisbon', city: 'Lisbon', country: 'Portugal', region: 'Mediterranean' },
  {
    name: 'Port of Liverpool',
    city: 'Liverpool',
    country: 'United Kingdom',
    region: 'UK & Ireland',
  },
  {
    name: 'Port of Long Beach',
    city: 'Long Beach',
    country: 'United States',
    region: 'US West Coast',
  },
  {
    name: 'Port of Los Angeles (San Pedro)',
    city: 'Los Angeles',
    country: 'United States',
    region: 'US West Coast',
  },
  { name: 'Port of Mahon', city: 'Mahon', country: 'Spain', region: 'Mediterranean' },
  { name: 'Port of Malaga', city: 'Malaga', country: 'Spain', region: 'Mediterranean' },
  { name: 'Port of Male', city: 'Male', country: 'Maldives', region: 'Asia Pacific' },
  { name: 'Port of Manaus', city: 'Manaus', country: 'Brazil', region: 'South America' },
  { name: 'Port of Manila', city: 'Manila', country: 'Philippines', region: 'Asia Pacific' },
  { name: 'Port of Marseille', city: 'Marseille', country: 'France', region: 'Mediterranean' },
  { name: 'Port of Mazatlan', city: 'Mazatlan', country: 'Mexico', region: 'Mexican Riviera' },
  { name: 'Port of Melbourne', city: 'Melbourne', country: 'Australia', region: 'Asia Pacific' },
  { name: 'Port of Messina', city: 'Messina', country: 'Italy', region: 'Mediterranean' },
  { name: 'PortMiami', city: 'Miami', country: 'United States', region: 'US East Coast' },
  { name: 'Port of Mobile', city: 'Mobile', country: 'United States', region: 'US Gulf Coast' },
  {
    name: 'Port of Monaco (Monte Carlo)',
    city: 'Monte Carlo',
    country: 'Monaco',
    region: 'Mediterranean',
  },
  { name: 'Port of Montego Bay', city: 'Montego Bay', country: 'Jamaica', region: 'Caribbean' },
  { name: 'Port of Montevideo', city: 'Montevideo', country: 'Uruguay', region: 'South America' },
  { name: 'Port of Montreal', city: 'Montreal', country: 'Canada', region: 'Canada & New England' },
  { name: 'Port of Mumbai', city: 'Mumbai', country: 'India', region: 'Asia Pacific' },
  { name: 'Port of Muscat', city: 'Muscat', country: 'Oman', region: 'Middle East' },
  { name: 'Port of Mykonos', city: 'Mykonos', country: 'Greece', region: 'Mediterranean' },
  { name: 'Port of Naha (Okinawa)', city: 'Naha', country: 'Japan', region: 'Asia Pacific' },
  { name: 'Port of Naples', city: 'Naples', country: 'Italy', region: 'Mediterranean' },
  { name: 'Port of Nassau', city: 'Nassau', country: 'Bahamas', region: 'Caribbean' },
  {
    name: 'Port of New Orleans',
    city: 'New Orleans',
    country: 'United States',
    region: 'US Gulf Coast',
  },
  {
    name: 'Manhattan Cruise Terminal',
    city: 'New York',
    country: 'United States',
    region: 'US East Coast',
  },
  { name: 'Port of Nice (Villefranche)', city: 'Nice', country: 'France', region: 'Mediterranean' },
  { name: 'Port of Norfolk', city: 'Norfolk', country: 'United States', region: 'US East Coast' },
  { name: 'Port of Noumea', city: 'Noumea', country: 'New Caledonia', region: 'South Pacific' },
  {
    name: 'Ocean Cay MSC Marine Reserve',
    city: 'Ocean Cay',
    country: 'Bahamas',
    region: 'Caribbean',
  },
  { name: 'Port of Oranjestad', city: 'Oranjestad', country: 'Aruba', region: 'Caribbean' },
  { name: 'Port of Osaka', city: 'Osaka', country: 'Japan', region: 'Asia Pacific' },
  { name: 'Port of Oslo', city: 'Oslo', country: 'Norway', region: 'Northern Europe' },
  { name: 'Port of Palermo', city: 'Palermo', country: 'Italy', region: 'Mediterranean' },
  {
    name: 'Port of Palma de Mallorca',
    city: 'Palma de Mallorca',
    country: 'Spain',
    region: 'Mediterranean',
  },
  {
    name: 'Port of Papeete (Tahiti)',
    city: 'Papeete',
    country: 'French Polynesia',
    region: 'South Pacific',
  },
  {
    name: 'Port of Penang (Georgetown)',
    city: 'Penang',
    country: 'Malaysia',
    region: 'Asia Pacific',
  },
  { name: 'Port of Piraeus (Athens)', city: 'Piraeus', country: 'Greece', region: 'Mediterranean' },
  {
    name: 'Port of Ponta Delgada (Azores)',
    city: 'Ponta Delgada',
    country: 'Portugal',
    region: 'Canary Islands & Atlantic',
  },
  { name: 'Port of Portland', city: 'Portland', country: 'United States', region: 'US East Coast' },
  { name: 'Port of Progreso (Merida)', city: 'Progreso', country: 'Mexico', region: 'Caribbean' },
  {
    name: 'Port of Puerto Limon',
    city: 'Puerto Limon',
    country: 'Costa Rica',
    region: 'Caribbean',
  },
  {
    name: 'Port of Puerto Plata',
    city: 'Puerto Plata',
    country: 'Dominican Republic',
    region: 'Caribbean',
  },
  {
    name: 'Port of Puerto Vallarta',
    city: 'Puerto Vallarta',
    country: 'Mexico',
    region: 'Mexican Riviera',
  },
  { name: 'Port of Punta Arenas', city: 'Punta Arenas', country: 'Chile', region: 'South America' },
  {
    name: 'Port of Punta Cana (La Romana)',
    city: 'Punta Cana',
    country: 'Dominican Republic',
    region: 'Caribbean',
  },
  {
    name: 'Port of Quebec City',
    city: 'Quebec City',
    country: 'Canada',
    region: 'Canada & New England',
  },
  { name: 'Port of Reykjavik', city: 'Reykjavik', country: 'Iceland', region: 'Northern Europe' },
  { name: 'Port of Rhodes', city: 'Rhodes', country: 'Greece', region: 'Mediterranean' },
  {
    name: 'Port of Rio de Janeiro',
    city: 'Rio de Janeiro',
    country: 'Brazil',
    region: 'South America',
  },
  { name: 'Port of Roatan', city: 'Roatan', country: 'Honduras', region: 'Caribbean' },
  { name: 'Port of Roseau', city: 'Roseau', country: 'Dominica', region: 'Caribbean' },
  {
    name: 'Port of Rostock (Warnemunde)',
    city: 'Rostock',
    country: 'Germany',
    region: 'Northern Europe',
  },
  {
    name: 'Port of Rotterdam',
    city: 'Rotterdam',
    country: 'Netherlands',
    region: 'Northern Europe',
  },
  {
    name: 'Port of Saint John',
    city: 'Saint John',
    country: 'Canada',
    region: 'Canada & New England',
  },
  {
    name: 'Port of San Diego',
    city: 'San Diego',
    country: 'United States',
    region: 'US West Coast',
  },
  {
    name: 'Port of San Francisco',
    city: 'San Francisco',
    country: 'United States',
    region: 'US West Coast',
  },
  { name: 'Port of San Juan', city: 'San Juan', country: 'Puerto Rico', region: 'Caribbean' },
  {
    name: 'Port of Santa Cruz de Tenerife',
    city: 'Santa Cruz de Tenerife',
    country: 'Spain',
    region: 'Canary Islands & Atlantic',
  },
  {
    name: 'Port of Santiago (San Antonio)',
    city: 'Santiago',
    country: 'Chile',
    region: 'South America',
  },
  {
    name: 'Port of Santorini (Thira)',
    city: 'Santorini',
    country: 'Greece',
    region: 'Mediterranean',
  },
  {
    name: 'Port of Santos (Sao Paulo)',
    city: 'Santos',
    country: 'Brazil',
    region: 'South America',
  },
  { name: 'Port of Savona', city: 'Savona', country: 'Italy', region: 'Mediterranean' },
  { name: 'Port of Seattle', city: 'Seattle', country: 'United States', region: 'US West Coast' },
  { name: 'Port of Seward', city: 'Seward', country: 'United States', region: 'Alaska' },
  {
    name: 'Port of Shanghai (Baoshan)',
    city: 'Shanghai',
    country: 'China',
    region: 'Asia Pacific',
  },
  { name: 'Port of Singapore', city: 'Singapore', country: 'Singapore', region: 'Asia Pacific' },
  { name: 'Port of Sitka', city: 'Sitka', country: 'United States', region: 'Alaska' },
  { name: 'Port of Skagway', city: 'Skagway', country: 'United States', region: 'Alaska' },
  {
    name: 'Port of Southampton',
    city: 'Southampton',
    country: 'United Kingdom',
    region: 'UK & Ireland',
  },
  { name: 'Port of Split', city: 'Split', country: 'Croatia', region: 'Mediterranean' },
  {
    name: 'Port of St. George (Grenada)',
    city: "St. George's",
    country: 'Grenada',
    region: 'Caribbean',
  },
  {
    name: "Port of St. John's (Antigua)",
    city: "St. John's",
    country: 'Antigua and Barbuda',
    region: 'Caribbean',
  },
  {
    name: 'Port of St. Kitts (Basseterre)',
    city: 'St. Kitts',
    country: 'Saint Kitts and Nevis',
    region: 'Caribbean',
  },
  {
    name: 'Port of St. Maarten (Philipsburg)',
    city: 'St. Maarten',
    country: 'Sint Maarten',
    region: 'Caribbean',
  },
  {
    name: 'Port of St. Petersburg',
    city: 'St. Petersburg',
    country: 'Russia',
    region: 'Northern Europe',
  },
  {
    name: 'Port of St. Thomas (Charlotte Amalie)',
    city: 'St. Thomas',
    country: 'US Virgin Islands',
    region: 'Caribbean',
  },
  { name: 'Port of Stockholm', city: 'Stockholm', country: 'Sweden', region: 'Northern Europe' },
  { name: 'Port of Suva', city: 'Suva', country: 'Fiji', region: 'South Pacific' },
  { name: 'Port of Sydney', city: 'Sydney', country: 'Australia', region: 'Asia Pacific' },
  { name: 'Port of Tallinn', city: 'Tallinn', country: 'Estonia', region: 'Northern Europe' },
  { name: 'Port of Tampa', city: 'Tampa', country: 'United States', region: 'US Gulf Coast' },
  { name: 'Port of Tauranga', city: 'Tauranga', country: 'New Zealand', region: 'Asia Pacific' },
  { name: 'Port of Tokyo (Yokohama)', city: 'Tokyo', country: 'Japan', region: 'Asia Pacific' },
  {
    name: 'Port of Tortola (Road Town)',
    city: 'Tortola',
    country: 'British Virgin Islands',
    region: 'Caribbean',
  },
  { name: 'Port of Toulon', city: 'Toulon', country: 'France', region: 'Mediterranean' },
  { name: 'Port of Trieste', city: 'Trieste', country: 'Italy', region: 'Mediterranean' },
  { name: 'Port of Tromso', city: 'Tromso', country: 'Norway', region: 'Northern Europe' },
  { name: 'Port of Ushuaia', city: 'Ushuaia', country: 'Argentina', region: 'South America' },
  { name: 'Port of Valletta', city: 'Valletta', country: 'Malta', region: 'Mediterranean' },
  { name: 'Port of Valparaiso', city: 'Valparaiso', country: 'Chile', region: 'South America' },
  {
    name: 'Port of Vancouver',
    city: 'Vancouver',
    country: 'Canada',
    region: 'Canada & New England',
  },
  { name: 'Port of Venice', city: 'Venice', country: 'Italy', region: 'Mediterranean' },
  {
    name: 'Port of Victoria (Canada)',
    city: 'Victoria',
    country: 'Canada',
    region: 'Canada & New England',
  },
  {
    name: 'Port of Victoria (Seychelles)',
    city: 'Victoria',
    country: 'Seychelles',
    region: 'Africa',
  },
  { name: 'Port of Vigo', city: 'Vigo', country: 'Spain', region: 'Northern Europe' },
  { name: 'Port of Whittier', city: 'Whittier', country: 'United States', region: 'Alaska' },
  { name: 'Port of Willemstad', city: 'Willemstad', country: 'Curacao', region: 'Caribbean' },
  { name: 'Port of Zanzibar', city: 'Zanzibar', country: 'Tanzania', region: 'Africa' },
  {
    name: 'Port of Zeebrugge (Bruges)',
    city: 'Zeebrugge',
    country: 'Belgium',
    region: 'Northern Europe',
  },
];

/** All unique regions, sorted alphabetically */
export const CRUISE_REGIONS: string[] = Array.from(
  new Set(CRUISE_PORTS.map((p) => p.region))
).sort();
