export interface CruiseLineInfo {
  name: string; // Full name (e.g., 'Royal Caribbean International')
  shortName: string; // Common short name (e.g., 'Royal Caribbean')
}

export const CRUISE_LINES: CruiseLineInfo[] = [
  { name: 'AIDA Cruises', shortName: 'AIDA' },
  { name: 'AmaWaterways', shortName: 'AmaWaterways' },
  { name: 'American Cruise Lines', shortName: 'American Cruise Lines' },
  { name: 'American Queen Voyages', shortName: 'American Queen' },
  { name: 'Atlas Ocean Voyages', shortName: 'Atlas Ocean' },
  { name: 'Aurelia', shortName: 'Aurelia' },
  { name: 'Avalon Waterways', shortName: 'Avalon' },
  { name: 'Azamara', shortName: 'Azamara' },
  { name: 'Carnival Cruise Line', shortName: 'Carnival' },
  { name: 'Celebrity Cruises', shortName: 'Celebrity' },
  { name: 'Celestyal Cruises', shortName: 'Celestyal' },
  { name: 'Costa Cruises', shortName: 'Costa' },
  { name: 'CroisiEurope', shortName: 'CroisiEurope' },
  { name: 'Crystal Cruises', shortName: 'Crystal' },
  { name: 'Cunard', shortName: 'Cunard' },
  { name: 'Disney Cruise Line', shortName: 'Disney' },
  { name: 'Dream Cruises', shortName: 'Dream Cruises' },
  { name: 'Emerald Cruises', shortName: 'Emerald' },
  { name: 'Explora Journeys', shortName: 'Explora' },
  { name: 'Fred. Olsen Cruise Lines', shortName: 'Fred. Olsen' },
  { name: 'Hapag-Lloyd Cruises', shortName: 'Hapag-Lloyd' },
  { name: 'Holland America Line', shortName: 'Holland America' },
  { name: 'Hurtigruten Expeditions', shortName: 'Hurtigruten' },
  { name: 'Lindblad Expeditions', shortName: 'Lindblad' },
  { name: 'Marella Cruises', shortName: 'Marella' },
  { name: 'MSC Cruises', shortName: 'MSC' },
  { name: 'Mystic Cruises', shortName: 'Mystic' },
  { name: 'Nicko Cruises', shortName: 'Nicko' },
  { name: 'Norwegian Cruise Line', shortName: 'Norwegian' },
  { name: 'Oceania Cruises', shortName: 'Oceania' },
  { name: 'P&O Cruises', shortName: 'P&O' },
  { name: 'P&O Cruises Australia', shortName: 'P&O Australia' },
  { name: 'Paul Gauguin Cruises', shortName: 'Paul Gauguin' },
  { name: 'Peregrine Adventures Cruises', shortName: 'Peregrine' },
  { name: 'Ponant', shortName: 'Ponant' },
  { name: 'Princess Cruises', shortName: 'Princess' },
  { name: 'Pullmantur Cruises', shortName: 'Pullmantur' },
  { name: 'Quark Expeditions', shortName: 'Quark' },
  { name: 'Regent Seven Seas Cruises', shortName: 'Regent' },
  { name: 'Resorts World Cruises', shortName: 'Resorts World' },
  { name: 'Riverside Luxury Cruises', shortName: 'Riverside' },
  { name: 'Riviera Travel', shortName: 'Riviera Travel' },
  { name: 'Royal Caribbean International', shortName: 'Royal Caribbean' },
  { name: 'Saga Cruises', shortName: 'Saga' },
  { name: 'Scenic Luxury Cruises & Tours', shortName: 'Scenic' },
  { name: 'Seabourn Cruise Line', shortName: 'Seabourn' },
  { name: 'SeaDream Yacht Club', shortName: 'SeaDream' },
  { name: 'Silversea Cruises', shortName: 'Silversea' },
  { name: 'Star Clippers', shortName: 'Star Clippers' },
  { name: 'Star Cruises', shortName: 'Star Cruises' },
  { name: 'Sunstone Ships', shortName: 'Sunstone' },
  { name: 'Swan Hellenic', shortName: 'Swan Hellenic' },
  { name: 'Tauck River Cruising', shortName: 'Tauck' },
  { name: 'The Ritz-Carlton Yacht Collection', shortName: 'Ritz-Carlton Yacht' },
  { name: 'TUI Cruises', shortName: 'TUI Cruises' },
  { name: 'UnCruise Adventures', shortName: 'UnCruise' },
  { name: 'Uniworld Boutique River Cruises', shortName: 'Uniworld' },
  { name: 'Variety Cruises', shortName: 'Variety' },
  { name: 'Viking', shortName: 'Viking' },
  { name: 'Viking River Cruises', shortName: 'Viking River' },
  { name: 'Virgin Voyages', shortName: 'Virgin Voyages' },
  { name: 'Viva Cruises', shortName: 'Viva' },
  { name: 'Vodohod', shortName: 'Vodohod' },
  { name: 'Windstar Cruises', shortName: 'Windstar' },
];
