/**
 * Public-holiday reference-data loader.
 *
 * Holidays are read-only data bundled with the app at `public/holidays/<ISO2>.json`
 * (generated by `scripts/generateHolidays.mjs`). This module fetches the file
 * for a single country, validates it, caches it in IndexedDB with a 7-day TTL,
 * and returns the holiday records — degrading gracefully (and loudly, on the
 * console) on every failure mode so the planner always renders.
 *
 * Mirrors `src/services/translation/translationFiles.ts` (the other
 * fetch-a-public-JSON loader) but collapsed, since there's a single consumer
 * (`holidayStore`).
 */
import type { CountryCode, HolidayFile, HolidayRecord } from '@/types/models';
import * as cache from '@/services/indexeddb/repositories/referenceDataCacheRepository';

const CACHE_TTL_MS = 7 * 24 * 60 * 60 * 1000; // 7 days — a regenerated dataset propagates within a week
const DATE_RE = /^\d{4}-\d{2}-\d{2}$/;

export interface HolidayLoadResult {
  /** Holiday records for the country (possibly empty — see `ok`). */
  records: HolidayRecord[];
  /** True when we have real data (from a fresh fetch or a cache hit). */
  ok: boolean;
  /**
   * True when the load failed transiently (network) AND there was no usable
   * cache — i.e. a retry on reconnect could help. False for a 404 ("country
   * not covered"), a corrupt file, or a successful load.
   */
  retryable: boolean;
}

const NOT_COVERED_LOGGED = new Set<CountryCode>(); // dedupe the "no published data" info log per session

/**
 * Validate the parsed file shape and return the clean record list. Drops
 * individual malformed records (logged) rather than rejecting the whole file;
 * returns null only if the top-level shape is wrong (a build bug).
 */
function validateFile(country: CountryCode, data: unknown): HolidayRecord[] | null {
  if (
    !data ||
    typeof data !== 'object' ||
    !Array.isArray((data as { holidays?: unknown }).holidays)
  ) {
    console.error(
      `[holidays] /holidays/${country}.json is malformed — expected { holidays: [...] }; got:`,
      data
    );
    return null;
  }
  const out: HolidayRecord[] = [];
  for (const raw of (data as HolidayFile).holidays) {
    const date = typeof raw?.date === 'string' ? raw.date : '';
    const name = typeof raw?.name === 'string' ? raw.name.trim() : '';
    if (!DATE_RE.test(date) || !name) {
      console.warn(
        `[holidays] dropping malformed record in ${country}.json (need a YYYY-MM-DD date + non-empty name):`,
        raw
      );
      continue;
    }
    const record: HolidayRecord = { date, name, type: 'public' };
    if (typeof raw.endDate === 'string' && DATE_RE.test(raw.endDate)) {
      if (raw.endDate < date) {
        console.warn(
          `[holidays] ${country}.json record has endDate < date — treating as single-day:`,
          raw
        );
      } else if (raw.endDate !== date) {
        record.endDate = raw.endDate;
      }
    }
    if (
      typeof raw.name_local === 'string' &&
      raw.name_local.trim() &&
      raw.name_local.trim() !== name
    ) {
      record.name_local = raw.name_local.trim();
    }
    out.push(record);
  }
  return out;
}

/** Fetch + validate the published file for a country. Returns null on 404 / network / corrupt. */
async function fetchHolidayFile(
  country: CountryCode
): Promise<
  { records: HolidayRecord[]; meta: HolidayFile['meta'] } | { networkError: true } | null
> {
  let res: Response;
  try {
    res = await fetch(`/holidays/${country}.json`);
  } catch (e) {
    console.warn(
      `[holidays] could not fetch /holidays/${country}.json (offline?) — will retry when back online:`,
      e
    );
    return { networkError: true };
  }
  if (!res.ok) {
    if (res.status === 404) {
      if (!NOT_COVERED_LOGGED.has(country)) {
        NOT_COVERED_LOGGED.add(country);
        console.warn(
          `[holidays] no published holiday data for "${country}" — the planner will show no public holidays for this country.`
        );
      }
      return null;
    }
    console.warn(`[holidays] /holidays/${country}.json returned ${res.status} ${res.statusText}`);
    return { networkError: true }; // a 5xx / proxy hiccup — treat like a transient failure
  }
  let json: unknown;
  try {
    json = await res.json();
  } catch (e) {
    console.error(`[holidays] /holidays/${country}.json is not valid JSON:`, e);
    return null;
  }
  const records = validateFile(country, json);
  if (records === null) return null;
  const meta = (json as HolidayFile).meta;
  return { records, meta };
}

/**
 * Load the public-holiday records for a country. Tries the IndexedDB cache
 * first (7-day TTL); otherwise fetches the published file, validates it,
 * caches it, and returns the records. Always resolves — never throws.
 */
export async function loadHolidays(country: CountryCode): Promise<HolidayLoadResult> {
  // 1) Fresh-enough cache?
  const cached = await cache.getCachedHolidays(country);
  const cacheFresh = cached && Date.now() - cached.cachedAt < CACHE_TTL_MS;
  if (cacheFresh) {
    return { records: cached.holidays, ok: true, retryable: false };
  }

  // 2) Fetch the published file.
  const fetched = await fetchHolidayFile(country);

  if (fetched && 'records' in fetched) {
    // Cache it (best-effort — the repo already swallows IndexedDB errors; the
    // extra `.catch` keeps the "never throws" contract bulletproof regardless).
    await cache
      .saveCachedHolidays({
        country,
        generatedAt: fetched.meta?.generatedAt ?? '',
        yearRange: fetched.meta?.yearRange ?? [0, 0],
        cachedAt: Date.now(),
        holidays: fetched.records,
      })
      .catch((e) => console.warn(`[holidays] failed to cache holidays for "${country}":`, e));
    return { records: fetched.records, ok: true, retryable: false };
  }

  // 3) Fetch failed — fall back to a stale cache if we have one.
  if (cached) {
    console.warn(
      `[holidays] using stale cached holidays for "${country}" (fetch failed; will refresh later).`
    );
    return { records: cached.holidays, ok: true, retryable: false };
  }

  // 4) Nothing. A network error with no cache is retryable; a 404 / corrupt file is not.
  const retryable = !!(fetched && 'networkError' in fetched);
  return { records: [], ok: false, retryable };
}
