/**
 * Recovery-passphrase generation + the one acceptance rule (login rethink Phase 3).
 *
 * NOT a strength meter — per the plan (Pass 2), no zxcvbn dependency, no scoring UI.
 * The default UX GENERATES a 4-word passphrase from the embedded wordlist via
 * `crypto.getRandomValues` (guaranteed ≥ 4 × log2(256) ≈ 32 bits… wordlist entropy —
 * see below — plus separator structure; the real defense is that user-chosen phrases are
 * the exception, not the rule). "Use my own" is allowed behind `isAcceptablePassphrase`.
 */

/**
 * 256 common, concrete, family-friendly English words (8 bits each → a generated
 * 4-word phrase carries 32 bits of wordlist entropy; combined with the requirement
 * that an attacker must ALSO hold the Drive file, this is the deliberate floor the
 * plan accepts for a memorable secret — families wanting more use the recovery kit).
 */
const WORDLIST = [
  'apple',
  'anchor',
  'autumn',
  'bacon',
  'badge',
  'bamboo',
  'banana',
  'basket',
  'beach',
  'beacon',
  'bean',
  'bear',
  'berry',
  'bicycle',
  'birch',
  'blanket',
  'bloom',
  'bluebird',
  'boat',
  'bonfire',
  'book',
  'boot',
  'bottle',
  'breeze',
  'brick',
  'bridge',
  'brook',
  'bubble',
  'bucket',
  'butter',
  'button',
  'cabin',
  'cactus',
  'camera',
  'candle',
  'canoe',
  'canyon',
  'carrot',
  'castle',
  'cedar',
  'cellar',
  'chair',
  'cherry',
  'chimney',
  'cinnamon',
  'circle',
  'cloud',
  'clover',
  'cobweb',
  'coconut',
  'comet',
  'compass',
  'cookie',
  'copper',
  'coral',
  'corn',
  'cotton',
  'cradle',
  'crayon',
  'cricket',
  'crystal',
  'daisy',
  'dolphin',
  'donkey',
  'drawer',
  'drum',
  'duck',
  'eagle',
  'earth',
  'echo',
  'ember',
  'engine',
  'falcon',
  'feather',
  'fern',
  'fiddle',
  'field',
  'firefly',
  'flag',
  'flame',
  'flower',
  'flute',
  'fog',
  'forest',
  'fountain',
  'fox',
  'frost',
  'garden',
  'garlic',
  'geyser',
  'ginger',
  'glacier',
  'glove',
  'goose',
  'grape',
  'grove',
  'hammer',
  'hammock',
  'harbor',
  'harvest',
  'hazel',
  'heron',
  'hill',
  'honey',
  'horizon',
  'horse',
  'hunter',
  'igloo',
  'island',
  'ivory',
  'jacket',
  'jaguar',
  'jasmine',
  'jelly',
  'jungle',
  'kayak',
  'kettle',
  'kitten',
  'kiwi',
  'ladder',
  'lagoon',
  'lantern',
  'lemon',
  'lighthouse',
  'lily',
  'lion',
  'lizard',
  'lobster',
  'locket',
  'lumber',
  'mango',
  'maple',
  'marble',
  'meadow',
  'melon',
  'mirror',
  'mitten',
  'monkey',
  'moon',
  'moss',
  'mountain',
  'mushroom',
  'nest',
  'noodle',
  'north',
  'oak',
  'ocean',
  'olive',
  'onion',
  'orange',
  'orchard',
  'otter',
  'owl',
  'oyster',
  'paddle',
  'pancake',
  'panda',
  'paper',
  'parrot',
  'peach',
  'pearl',
  'pebble',
  'pelican',
  'pencil',
  'penguin',
  'pepper',
  'petal',
  'piano',
  'pickle',
  'pigeon',
  'pillow',
  'pine',
  'planet',
  'plum',
  'pocket',
  'pond',
  'pony',
  'poppy',
  'potato',
  'prairie',
  'pumpkin',
  'puzzle',
  'quill',
  'rabbit',
  'raccoon',
  'radish',
  'rainbow',
  'raven',
  'reef',
  'ribbon',
  'river',
  'robin',
  'rocket',
  'rooster',
  'rose',
  'ruby',
  'saddle',
  'sailboat',
  'salmon',
  'sand',
  'sapphire',
  'seal',
  'shell',
  'silver',
  'sky',
  'sled',
  'snail',
  'snow',
  'socks',
  'sparrow',
  'spider',
  'spoon',
  'spring',
  'sprout',
  'squirrel',
  'stone',
  'storm',
  'stove',
  'straw',
  'stream',
  'sugar',
  'summer',
  'sunset',
  'swan',
  'table',
  'teapot',
  'thunder',
  'tiger',
  'timber',
  'toast',
  'tomato',
  'torch',
  'trail',
  'train',
  'tulip',
  'tunnel',
  'turtle',
  'valley',
  'velvet',
  'violet',
  'wagon',
  'walnut',
  'water',
  'whale',
  'wheat',
  'willow',
  'window',
  'winter',
  'wolf',
  'wonder',
  'woodpecker',
  'wren',
  'yarn',
  'yogurt',
  'zebra',
  'zephyr',
] as const;

export const PASSPHRASE_WORD_COUNT = 4;
export const PASSPHRASE_MIN_LENGTH = 14;
export const PASSPHRASE_MIN_TOKENS = 3;

/** Generate a memorable 4-word passphrase (`word-word-word-word`). */
export function generatePassphrase(): string {
  const idx = crypto.getRandomValues(new Uint8Array(PASSPHRASE_WORD_COUNT));
  return Array.from(idx, (i) => WORDLIST[i % WORDLIST.length]).join('-');
}

export type PassphraseVerdict =
  { ok: true } | { ok: false; reason: 'too-short' | 'too-few-words' | 'matches-name' };

/**
 * The ONE acceptance rule for a user-chosen passphrase: min 14 chars AND min 3 distinct
 * word tokens, and never equal to the family name or a member name (case-insensitive,
 * separators ignored). Deliberately not a meter.
 */
export function checkPassphrase(
  passphrase: string,
  names: { familyName?: string; memberNames?: string[] } = {}
): PassphraseVerdict {
  const trimmed = passphrase.trim();
  if (trimmed.length < PASSPHRASE_MIN_LENGTH) return { ok: false, reason: 'too-short' };
  const tokens = new Set(
    trimmed
      .toLowerCase()
      .split(/[\s\-_.]+/)
      .filter(Boolean)
  );
  if (tokens.size < PASSPHRASE_MIN_TOKENS) return { ok: false, reason: 'too-few-words' };

  const canon = (v: string) => v.toLowerCase().replace(/[\s\-_.]+/g, '');
  const canonPhrase = canon(trimmed);
  const candidates = [names.familyName, ...(names.memberNames ?? [])].filter(
    (n): n is string => !!n
  );
  if (candidates.some((n) => canon(n) === canonPhrase)) {
    return { ok: false, reason: 'matches-name' };
  }
  return { ok: true };
}
