import { describe, expect, it } from 'vitest';
import { countryForTimeZone } from './timeZoneCountry.mjs';
import { ZONE_COUNTRIES } from './timeZoneCountryData.mjs';

describe('countryForTimeZone (#125 deviceCountry)', () => {
  it.each([
    ['Asia/Singapore', 'SG'],
    ['America/Los_Angeles', 'US'],
    // A backward link alias (V8 still reports this name) takes its target's country.
    ['Asia/Calcutta', 'IN'],
    // Three-part names are valid zones.
    ['America/Argentina/Buenos_Aires', 'AR'],
    // zone.tab wins over a link: Bratislava is SK even though it links to Europe/Prague (CZ).
    ['Europe/Bratislava', 'SK'],
    ['Europe/Prague', 'CZ'],
    // Surrounding whitespace is trimmed.
    ['  Asia/Singapore  ', 'SG'],
  ])('%s -> %s', (zone, cc) => {
    expect(countryForTimeZone(zone)).toBe(cc);
  });

  it.each([
    ['UTC', 'UTC'],
    ['Etc/UTC', 'Etc/UTC'],
    ['Etc/GMT+8', 'Etc/GMT+8'],
    ['an unknown zone', 'Mars/Olympus_Mons'],
    ['garbage', 'not a zone at all'],
    ['a single-segment legacy name', 'Singapore'],
    ['a four-part name', 'A/B/C/D'],
    ['a prototype key', 'constructor/prototype'],
    ['__proto__', '__proto__'],
    ['a 300-char string', `Asia/${'x'.repeat(295)}`],
    ['an empty string', ''],
  ])('%s is null', (_label, zone) => {
    expect(countryForTimeZone(zone)).toBeNull();
  });

  it('is null for every non-string', () => {
    for (const v of [undefined, null, 42, {}, [], true]) {
      expect(countryForTimeZone(v)).toBeNull();
    }
  });
});

describe('ZONE_COUNTRIES (generated by scripts/gen-timezone-countries.mjs)', () => {
  it('is frozen', () => {
    expect(Object.isFrozen(ZONE_COUNTRIES)).toBe(true);
  });

  it('every value is two upper-case letters', () => {
    for (const cc of Object.values(ZONE_COUNTRIES)) expect(cc).toMatch(/^[A-Z]{2}$/);
  });

  it('every key is reachable through countryForTimeZone (no dead entries)', () => {
    for (const [zone, cc] of Object.entries(ZONE_COUNTRIES)) {
      expect(countryForTimeZone(zone)).toBe(cc);
    }
  });
});
