#!/usr/bin/env node
/**
 * Migration-change generator (#117, plan `docs/plans/2026-10-01-crdt-merge-safe-writes.md` §F).
 *
 * `migrateDoc` creates a collection that is ABSENT from an older pod by applying a committed,
 * pre-generated Automerge change instead of an ordinary `d[name] = {}`. Every device then
 * applies the SAME change, so every device holds the SAME map object and concurrent writes into
 * the new collection merge instead of one device's map silently winning.
 *
 * For each name in `COLLECTION_NAMES` that is missing from `MIGRATION_CHANGES`, this builds:
 *
 *   actor = sha256("beanies-migration:" + name) as hex, first 16 chars
 *   Automerge.init({ actor }) -> change({ time: 0 }, d => { d[name] = {} }) -> getLastLocalChange
 *
 * and APPENDS it, base64-encoded, to `src/services/automerge/worker/migrationChanges.ts`.
 *
 * ⚠️ APPEND-ONLY, AND THERE IS NO FLAG TO CHANGE THAT. An entry that exists is never rewritten:
 * its bytes are already inside families' pods, and a regenerated change (a different Automerge
 * version can encode the same change differently) would collide on actor+seq with that copy.
 * See the generated file's header.
 *
 * `COLLECTION_NAMES` and the existing table are read by importing the TypeScript sources
 * directly: Node 22.18+ / 24 strips types natively, and both files have only type-level imports.
 *
 * Usage:
 *   node scripts/generateMigrationChanges.mjs     (or: npm run generate:migration-changes)
 */

import { createHash } from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import * as Automerge from '@automerge/automerge';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..');
// Read from disk: the package's `exports` map does not expose `./package.json`.
const AUTOMERGE_VERSION = JSON.parse(
  fs.readFileSync(
    path.join(ROOT, 'node_modules', '@automerge', 'automerge', 'package.json'),
    'utf8'
  )
).version;
const TYPES_PATH = path.join(ROOT, 'src', 'types', 'automerge.ts');
const TABLE_PATH = path.join(ROOT, 'src', 'services', 'automerge', 'worker', 'migrationChanges.ts');

/** The line new entries are inserted above. The generator refuses a file without exactly one. */
const SENTINEL = '  // generateMigrationChanges.mjs appends new entries above this line.';

const HEADER = `/* eslint-disable no-secrets/no-secrets -- public Automerge change bytes (high entropy by nature), not secrets */
// GENERATED by scripts/generateMigrationChanges.mjs (npm run generate:migration-changes).
// APPEND-ONLY. Never edit, reorder or regenerate an existing entry by hand.
//
// One pre-built Automerge change per collection (#117, plan
// docs/plans/2026-10-01-crdt-merge-safe-writes.md section F, ADR-039). \`migrateDoc\` applies the
// stored change for a collection that is ABSENT from a pod, so every device that migrates the
// pod creates the SAME map object and concurrent writes into the new collection merge. An
// ordinary \`d[name] = {}\` per device creates two different objects, and only one device's
// entities survive the merge.
//
// Each change: actor = sha256("beanies-migration:" + name) hex, first 16 chars; seq 1;
// deps []; time 0; one op creating \`{ [name]: {} }\` at the root. No device ever writes as
// these actors.
//
// WHY THE BYTES ARE NEVER REGENERATED: these exact bytes are already inside families' pods.
// Automerge must keep loading old changes, so they stay readable after an upgrade. A
// REGENERATED change could encode differently under a newer Automerge and then collide on
// actor+seq with the copy already in a pod (same actor, same seq, different hash), which
// Automerge treats as a corrupt history. So there is deliberately no "regenerate and compare"
// test, and the generator only ever appends entries for collections the table lacks.
//
// Renames do not exist in this model: a renamed collection is a NEW collection with a NEW
// entry. A removed collection's entry may be deleted (the Record type then requires it).
`;

function actorFor(name) {
  return createHash('sha256')
    .update('beanies-migration:' + name)
    .digest('hex')
    .slice(0, 16);
}

function buildChange(name) {
  const created = Automerge.change(Automerge.init({ actor: actorFor(name) }), { time: 0 }, (d) => {
    d[name] = {};
  });
  const change = Automerge.getLastLocalChange(created);
  if (!change) throw new Error(`no change produced for "${name}"`);
  // Self-check before anything is written: the change must be exactly what migrateDoc expects.
  const decoded = Automerge.decodeChange(change);
  if (
    decoded.actor !== actorFor(name) ||
    decoded.seq !== 1 ||
    decoded.deps.length !== 0 ||
    decoded.time !== 0 ||
    decoded.ops.length !== 1
  ) {
    throw new Error(`change for "${name}" does not have the required shape`);
  }
  return Buffer.from(change).toString('base64');
}

/** One entry, laid out the way Prettier (printWidth 100) would, so the output is format-clean. */
function entryLine(name, b64) {
  const oneLine = `  ${name}: '${b64}',`;
  return oneLine.length <= 100 ? oneLine : `  ${name}:\n    '${b64}',`;
}

async function loadModule(file) {
  // Cache-busting query: the verify step re-imports the table after writing it.
  return import(`${pathToFileURL(file).href}?t=${Date.now()}`);
}

async function main() {
  const { COLLECTION_NAMES } = await loadModule(TYPES_PATH);
  if (!Array.isArray(COLLECTION_NAMES) || COLLECTION_NAMES.length === 0) {
    throw new Error(`could not read COLLECTION_NAMES from ${TYPES_PATH}`);
  }

  const exists = fs.existsSync(TABLE_PATH);
  const original = exists ? fs.readFileSync(TABLE_PATH, 'utf8') : null;
  const existing = exists ? (await loadModule(TABLE_PATH)).MIGRATION_CHANGES : {};

  const missing = COLLECTION_NAMES.filter((name) => !Object.hasOwn(existing, name));
  const stale = Object.keys(existing).filter((name) => !COLLECTION_NAMES.includes(name));
  for (const name of stale) {
    console.warn(
      `! "${name}" has an entry but is no longer a collection. Left untouched; delete it by hand if the collection is gone for good.`
    );
  }
  if (missing.length === 0) {
    console.log(
      `Nothing to add: all ${COLLECTION_NAMES.length} collections have a stored change. No file written.`
    );
    return;
  }

  const added = missing.map((name) => ({ name, b64: buildChange(name) }));
  const block = added.map(({ name, b64 }) => entryLine(name, b64)).join('\n');
  const stamp = `  // Appended ${new Date().toISOString().slice(0, 10)} with @automerge/automerge ${AUTOMERGE_VERSION}.`;

  let next;
  if (original === null) {
    next =
      `${HEADER}import type { CollectionName } from '@/types/automerge';\n\n` +
      `/** Base64 Automerge change per collection. Typed exhaustively: a collection without an entry\n` +
      ` *  is a compile error, so a new collection cannot ship without its deterministic creation. */\n` +
      `export const MIGRATION_CHANGES: Record<CollectionName, string> = {\n` +
      `${stamp}\n${block}\n${SENTINEL}\n};\n`;
  } else {
    const parts = original.split(`${SENTINEL}\n`);
    if (parts.length !== 2) {
      throw new Error(
        `refusing to write: ${TABLE_PATH} must contain the sentinel line exactly once:\n${SENTINEL}`
      );
    }
    next = `${parts[0]}${stamp}\n${block}\n${SENTINEL}\n${parts[1]}`;
  }

  fs.writeFileSync(TABLE_PATH, next);

  // Verify append-only: every pre-existing entry is byte-identical and every new one landed.
  // On any mismatch the original file is restored, so a failed run leaves nothing behind.
  try {
    const after = (await loadModule(TABLE_PATH)).MIGRATION_CHANGES;
    for (const [name, b64] of Object.entries(existing)) {
      if (after[name] !== b64) throw new Error(`existing entry "${name}" changed`);
    }
    for (const { name, b64 } of added) {
      if (after[name] !== b64) throw new Error(`new entry "${name}" did not land`);
    }
  } catch (e) {
    if (original === null) fs.unlinkSync(TABLE_PATH);
    else fs.writeFileSync(TABLE_PATH, original);
    throw new Error(`verify failed, file restored: ${e.message}`, { cause: e });
  }

  console.log(
    `Appended ${added.length} migration change(s) to ${path.relative(ROOT, TABLE_PATH)} ` +
      `(@automerge/automerge ${AUTOMERGE_VERSION}):`
  );
  for (const { name } of added) console.log(`  + ${name}  actor ${actorFor(name)}`);
  console.log(`Kept ${Object.keys(existing).length} existing entr(y/ies) untouched.`);
}

main().catch((e) => {
  console.error(`generateMigrationChanges: ${e.message}`);
  process.exitCode = 1;
});
