/* eslint-disable no-secrets/no-secrets -- public Automerge change bytes (high entropy by nature), not secrets */
// GENERATED by scripts/generateMigrationChanges.mjs (npm run generate:migration-changes).
// APPEND-ONLY. Never edit, reorder or regenerate an existing entry by hand.
//
// One pre-built Automerge change per migrated root map: every collection, plus the Phase 2
// `counterDeltas` map (#117, plan docs/plans/2026-10-01-crdt-merge-safe-writes.md section F,
// ADR-039). `migrateDoc` applies the stored change for a key that is ABSENT from a pod, so
// every device that migrates the pod creates the SAME map object and concurrent writes into it
// merge. An
// ordinary `d[name] = {}` per device creates two different objects, and only one device's
// entities survive the merge.
//
// Each change: actor = sha256("beanies-migration:" + name) hex, first 16 chars; seq 1;
// deps []; time 0; one op creating `{ [name]: {} }` at the root. No device ever writes as
// these actors.
//
// WHY THE BYTES ARE NEVER REGENERATED: these exact bytes are already inside families' pods.
// Automerge must keep loading old changes, so they stay readable after an upgrade. A
// REGENERATED change could encode differently under a newer Automerge and then collide on
// actor+seq with the copy already in a pod (same actor, same seq, different hash), which
// Automerge treats as a corrupt history. So there is deliberately no "regenerate and compare"
// test, and the generator only ever appends entries for keys the table lacks.
//
// Renames do not exist in this model: a renamed collection is a NEW collection with a NEW
// entry. A removed collection's entry may be deleted (the Record type then requires it).
import type { MigratedRootKey } from '@/types/automerge';

/** Base64 Automerge change per migrated root key. Typed exhaustively: a key in
 *  `MIGRATED_ROOT_KEYS` without an entry is a compile error, so a new collection (or root
 *  map) cannot ship without its deterministic creation. */
export const MIGRATION_CHANGES: Record<MigratedRootKey, string> = {
  // Appended 2026-10-01 with @automerge/automerge 3.4.1.
  familyMembers: 'hW9Kg17f0JkBMAAImmBlDYU+qacBAQAAAAUVDzQBQgJWAnACfw1mYW1pbHlNZW1iZXJzAX8AfwB/AA==',
  accounts: 'hW9Kg6h7TZwBKwAIyoN7KD7Acf4BAQAAAAUVCjQBQgJWAnACfwhhY2NvdW50cwF/AH8AfwA=',
  transactions: 'hW9Kg/UvxaYBLwAIYZXBO7tJ/GIBAQAAAAUVDjQBQgJWAnACfwx0cmFuc2FjdGlvbnMBfwB/AH8A',
  assets: 'hW9Kg/Rt4ZgBKQAIxbj+UQovt8gBAQAAAAUVCDQBQgJWAnACfwZhc3NldHMBfwB/AH8A',
  goals: 'hW9KgxFJ6AIBKAAIxrbxAosddEQBAQAAAAUVBzQBQgJWAnACfwVnb2FscwF/AH8AfwA=',
  budgets: 'hW9Kg4c2p/UBKgAIv+sBfUZd6YkBAQAAAAUVCTQBQgJWAnACfwdidWRnZXRzAX8AfwB/AA==',
  recurringItems:
    'hW9Kg6hhWfIBMQAI8qFmPJs26rwBAQAAAAUVEDQBQgJWAnACfw5yZWN1cnJpbmdJdGVtcwF/AH8AfwA=',
  todos: 'hW9Kgyxp1L8BKAAIBUun+oQzvQQBAQAAAAUVBzQBQgJWAnACfwV0b2RvcwF/AH8AfwA=',
  lists: 'hW9Kg7yJpQABKAAIOEg44Cb6u5oBAQAAAAUVBzQBQgJWAnACfwVsaXN0cwF/AH8AfwA=',
  activities: 'hW9KgwJ5W8UBLQAI5RIZP/RW9aABAQAAAAUVDDQBQgJWAnACfwphY3Rpdml0aWVzAX8AfwB/AA==',
  vacations: 'hW9Kg6ZmJQUBLAAIZ7BKqwpW5TYBAQAAAAUVCzQBQgJWAnACfwl2YWNhdGlvbnMBfwB/AH8A',
  photos: 'hW9Kg8bbtfABKQAIPXE/wGWSalcBAQAAAAUVCDQBQgJWAnACfwZwaG90b3MBfwB/AH8A',
  favorites: 'hW9Kg4hxd2wBLAAIHidE6dfMdycBAQAAAAUVCzQBQgJWAnACfwlmYXZvcml0ZXMBfwB/AH8A',
  sayings: 'hW9KgyPAo9ABKgAIbtLkDti0D5MBAQAAAAUVCTQBQgJWAnACfwdzYXlpbmdzAX8AfwB/AA==',
  memberNotes: 'hW9Kg2tMyx8BLgAIiOQaXIaR5ogBAQAAAAUVDTQBQgJWAnACfwttZW1iZXJOb3RlcwF/AH8AfwA=',
  allergies: 'hW9Kg52J+BgBLAAIUC+WPsGUu0QBAQAAAAUVCzQBQgJWAnACfwlhbGxlcmdpZXMBfwB/AH8A',
  medications: 'hW9Kg+a3WzYBLgAIohBU6HPJuZ8BAQAAAAUVDTQBQgJWAnACfwttZWRpY2F0aW9ucwF/AH8AfwA=',
  medicationLogs:
    'hW9Kg3jNhO4BMQAI6+4G8jMRB1MBAQAAAAUVEDQBQgJWAnACfw5tZWRpY2F0aW9uTG9ncwF/AH8AfwA=',
  milestones: 'hW9Kg7RPt+QBLQAIzxctVHUsZfABAQAAAAUVDDQBQgJWAnACfwptaWxlc3RvbmVzAX8AfwB/AA==',
  recipes: 'hW9KgyLT7jYBKgAIYwvY7g246LsBAQAAAAUVCTQBQgJWAnACfwdyZWNpcGVzAX8AfwB/AA==',
  cookLogs: 'hW9Kg2T0DJIBKwAIMPhpjE6c8WABAQAAAAUVCjQBQgJWAnACfwhjb29rTG9ncwF/AH8AfwA=',
  mealPlans: 'hW9Kgy6OHuwBLAAIAGXmOD/kQkgBAQAAAAUVCzQBQgJWAnACfwltZWFsUGxhbnMBfwB/AH8A',
  emergencyContacts:
    'hW9Kg96Kav0BNAAISNMXM4V94woBAQAAAAUVEzQBQgJWAnACfxFlbWVyZ2VuY3lDb250YWN0cwF/AH8AfwA=',
  notificationReads:
    'hW9KgxTNusMBNAAIGS9u4tmGp0oBAQAAAAUVEzQBQgJWAnACfxFub3RpZmljYXRpb25SZWFkcwF/AH8AfwA=',
  calendarConnections:
    'hW9Kgys8J2gBNgAINzjtdbT5/04BAQAAAAUVFTQBQgJWAnACfxNjYWxlbmRhckNvbm5lY3Rpb25zAX8AfwB/AA==',
  calendarEventLinks:
    'hW9Kg4u0fNEBNQAI4zlOopwRC4UBAQAAAAUVFDQBQgJWAnACfxJjYWxlbmRhckV2ZW50TGlua3MBfwB/AH8A',
  driveConnections:
    'hW9Kg+qxZIMBMwAIPcDhzLCt1nwBAQAAAAUVEjQBQgJWAnACfxBkcml2ZUNvbm5lY3Rpb25zAX8AfwB/AA==',
  overlapAcknowledgments:
    'hW9Kg5k0dv0BOQAI05LzGZDWuf4BAQAAAAUVGDQBQgJWAnACfxZvdmVybGFwQWNrbm93bGVkZ21lbnRzAX8AfwB/AA==',
  listCycles: 'hW9Kg8GkNo4BLQAIyoL2VqBQcrkBAQAAAAUVDDQBQgJWAnACfwpsaXN0Q3ljbGVzAX8AfwB/AA==',
  removedMembers:
    'hW9KgzHo2O4BMQAIUES+eRHVAo0BAQAAAAUVEDQBQgJWAnACfw5yZW1vdmVkTWVtYmVycwF/AH8AfwA=',
  responsibilityCards:
    'hW9Kg77DI2kBNgAIKy8/HXjKxfkBAQAAAAUVFTQBQgJWAnACfxNyZXNwb25zaWJpbGl0eUNhcmRzAX8AfwB/AA==',
  responsibilityMoves:
    'hW9Kg5YAtZwBNgAIfB25wKDnU68BAQAAAAUVFTQBQgJWAnACfxNyZXNwb25zaWJpbGl0eU1vdmVzAX8AfwB/AA==',
  responsibilityCheckIns:
    'hW9Kg/bK6TQBOQAIwgaaIR98sx4BAQAAAAUVGDQBQgJWAnACfxZyZXNwb25zaWJpbGl0eUNoZWNrSW5zAX8AfwB/AA==',
  // Appended 2026-10-03 with @automerge/automerge 3.4.1.
  counterDeltas: 'hW9Kg23iG3ABMAAI7QPUHg/rglIBAQAAAAUVDzQBQgJWAnACfw1jb3VudGVyRGVsdGFzAX8AfwB/AA==',
  // generateMigrationChanges.mjs appends new entries above this line.
};
